---

- hosts: all
  become: true
  tasks:

  - name: this will the install apache2 and php package and update packages
    apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"
