---

- hosts: all
  become: true
  tasks:

  - name: update packages of the server
    apt:
      update_cache: yes

  - name: this will the remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
